services:
  relationapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: relationapp:latest
    ports:
      - "8080:8080"  # Container port 80, Host port 8080
      - "8900:8900" # Container port 8081, Host port 8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # .NET mühiti
    volumes:
      - ./logs:/app/logs  
    restart: always  # Xidmət dayanarsa avtomatik olaraq yenidən başlasın

